// CrashReporter application.
// Copyright (c) 2009 by Elijah Zarezky,
// All rights reserved.

// CrashReporterApp.h - interface of the CCrashReporterApp class

// initially generated by AfxScratch v1.1.4778 on 14.08.2009 at 18:13:40
// visit http://zarezky.spb.ru/projects/afx_scratch.html for more info

#if !defined(__CrashReporterApp_h)
#define __CrashReporterApp_h

#if defined(_MSC_VER) && (_MSC_VER > 1000)
#pragma once
#endif   // _MSC_VER

class CCrashReporterApp: public CWinApp
{
	DECLARE_DYNAMIC(CCrashReporterApp)
	DECLARE_MESSAGE_MAP()

// construction/destruction
public:
	CCrashReporterApp(void);
	virtual ~CCrashReporterApp(void);

// operations
public:
	HICON LoadSmIcon(LPCTSTR pszResName);

// overridables
public:
	virtual BOOL InitInstance(void);

// diagnostic services
#if defined(_DEBUG)
public:
	virtual void AssertValid(void) const;
	virtual void Dump(CDumpContext& dumpCtx) const;
#endif
};

#endif   // __CrashReporterApp_h

// end of file
